name: deployment

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  push-to-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dennthrow/turbo-spoon:latest

  deploy-testing:
    runs-on: ubuntu-20.04
    environment: "testing"
    needs: push-to-docker
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_TEST }}
          webhook_secret: ""

  deploy-production:
    runs-on: ubuntu-20.04
    environment: "production"
    needs: [push-to-docker, deploy-testing]
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_PROD }}
          webhook_secret: ""
