name: push-to-docker

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dennthrow/turbo-spoon:latest
          
  approval:
    runs-on: ubuntu-20.04
    
    steps:     
      - name: Request approval
        id: approval_step
        uses: actions/request-approval@v2
        with:
          reviewers: 'Calvahar'
          message: 'Please review the deployment on the testing-cluster and approve if all works well.'
      
      - name: Send webhook
        if: steps.approval_step.outputs.approved == 'true'
        uses: actions/webhooks@v2
        with:
          args: 'https://e4a8-145-220-75-5.eu.ngrok.io/github'
